# Generated by Django 3.0.7 on 2020-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('term', models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term')], max_length=15)),
                ('credit_score', models.FloatField()),
                ('year_in_current_job', models.CharField(choices=[('< 1 year', '< 1 year'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('4 years', '4 years'), ('5 years', '5 years'), ('6 years', '6 years'), ('7 years', '7 years'), ('8 years', '8 years'), ('9 years', '9 years'), ('10+ years', '10+ years')], max_length=15)),
                ('home_ownership', models.CharField(choices=[('Home Mortgage', 'Home Mortgage'), ('Own Home', 'Own Home'), ('Rent', 'Rent'), ('Have Mortgage', 'HaveMortgage')], max_length=30)),
                ('purpose', models.CharField(choices=[('Home Improvements', 'Home Improvements'), ('Debt Consolidation', 'Debt Consolidation'), ('Buy House', 'Buy House'), ('Business Loan', 'Business Loan'), ('Buy a Car', 'Buy a Car'), ('Other', 'Other'), ('Take a Trip', 'Take a Trip'), ('Medical Bills', 'Medical Bills'), ('Educational Expenses', 'Educational Expenses'), ('Other', 'Other')], max_length=30)),
                ('years_credit_history', models.FloatField()),
                ('num_open_acc', models.IntegerField()),
            ],
        ),
    ]
