# Generated by Django 3.0.7 on 2020-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purpose',
            field=models.CharField(choices=[('Home Improvements', 'Home Improvements'), ('Debt Consolidation', 'Debt Consolidation'), ('Buy House', 'Buy House'), ('Business Loan', 'Business Loan'), ('Buy a Car', 'Buy a Car'), ('Other', 'Other'), ('Take a Trip', 'Take a Trip'), ('Medical Bills', 'Medical Bills'), ('Educational Expenses', 'Educational Expenses')], max_length=30),
        ),
    ]
